[DS-2778] Add in all Dev Jam model architectures
ShopRunner/collie_recs pull request #17
Opened 2021-05-12 21:33 UTC by nathancooperjones

TODO when this PR is ready for review. 

## Describe the big picture - why are we doing this?

## Any additional details to clarify code in the PR?

## How is this tested?

## Pull Request Checklist
 - [ ] Pull request includes a description of why we are doing this
 - [ ] ``CHANGELOG`` has been updated
 - [ ] Version in ``_version.py`` has been updated
 - [ ] All tests in the ``tests`` folder pass with a local build
 - [ ] ``README`` has been updated (if applicable)
 - [ ] Documentation in ``docs`` has been updated (if applicable)
 - [ ] ``requirements.txt`` and ``requirements-dev.txt`` have been recompiled (if applicable)

## Screenshots or GIFs?

2021-06-03 19:53 UTC, htorrence requested changes
Sorry for being extremely slow! I read through the different model classes and this looks really great! I mostly had documentation questions/clarifications.

Having the bulk of a very long/extensive docstring copied so many times is a little tricky for changes, I poked around a bit and I wonder if this format could work, with the parameters in the base class docstring? That only works if all the parameters are the same, which I haven't checked carefully. Anyway, definitely not required, but maybe worth trying sometime.

https://stackoverflow.com/questions/2025562/inherit-docstrings-in-python-class-inheritance

2021-06-03 19:53 UTC, htorrence commented on collie_recs/model/mlp_matrix_factorization.py
> +        Simple matrix factorization for a single user and item looks like:
This example seems odd to me when it's not what the model is doing - is that your intention here, to compare the other versions to simple MF?

2021-06-04 20:37 UTC, nathancooperjones commented on collie_recs/model/mlp_matrix_factorization.py
> +        Simple matrix factorization for a single user and item looks like:
Typo, whoops! Good catch!

2021-06-04 22:23 UTC, nathancooperjones commented on CHANGELOG.md
> + - filename for ``HybridPretrainedModel`` to ``hybrid_pretrained_matrix_factorization.py``. The former model filepath is now deprecated and will be removed in future version ``0.X.0``
The class itself is removed, but the file isn't removed yet. I'll remove the file itself in a future version.

2021-06-07 15:28 UTC, htorrence requested changes
I think this approach will work! I left a couple of suggestions.

2021-06-07 15:28 UTC, htorrence commented on collie_recs/model/base/docstring.py
> +    child_docstring_list = child_docstring.split(NEWLINE_CHARACTER)
Okay, I poked around a bit more because this parsing stuff is fun. I'm assuming you went this way to get the reference section - it looks like those get stashed under this meta list, I think you can grab the remaining section like this without having to maintain our own regexs for this stuff (I'm highly avoidant of that, it just gets really fragile in my experience):
```
print('\n\n'.join([
    x.args[0].title() + '\n' +'-'*len(x.args[0]) + '\n' + x.description 
    for x in parsed.meta
    if type(x) == docstring_parser.DocstringMeta
]))
```
It looks like the library pulls out parameters, returns, raises, and deprecation as particular attributes, then leaves everything else as DocstringMeta objects in this list https://github.com/rr-/docstring_parser/blob/master/docstring_parser/common.py#L121

This approach should let you avoid having to do this much validation yourself, and handle any other sections that pop up in the future

2021-06-07 17:04 UTC, nathancooperjones commented on .github/workflows/ci.yaml
Suddenly, GitHub is running out of disk space trying to build the massive container. Oh whale 🐋

2021-06-07 19:09 UTC, htorrence commented on .github/workflows/ci.yaml
sounds good, I think it's fine to leave out

2021-06-11 13:41 UTC, htorrence approved these changes
I think this looks good! At some point I think there are probably a few things we can streamline, but this fixes the "keeping everything in sync" issue, and seems decently robust to me. 

Plus all the cool new architectures, which were originally the point! 🙂

2021-06-11 13:41 UTC, htorrence commented on collie_recs/model/nonlinear_matrix_factorization.py
> +    # NOTE: the full docstring is merged in with ``BasePipeline``'s using ``merge_docstrings``
I might add one more line with something like this? Just so it's clear what "merged" means at a glance
```
# only descriptions of new or changed parameters are included in this docstring
```

2021-06-11 13:44 UTC, nathancooperjones commented
> I think this looks good! At some point I think there are probably a few things we can streamline, but this fixes the "keeping everything in sync" issue, and seems decently robust to me.
> 
> Plus all the cool new architectures, which were originally the point! 🙂

I think at some point, it would be nice to go back and make it robust to the point where all sections can be represented (Returns, Raises, etc.) so we can use this generally throughout the library. Could be a fun day's work in the future!

2021-06-11 13:57 UTC, merged