[DS-3006] Add explicit data support
ShopRunner/collie_recs pull request #20
Opened 2021-06-10 00:42 UTC by nathancooperjones

## Describe the big picture - why are we doing this?
Closes https://github.com/ShopRunner/collie_recs/issues/10. 

## Any additional details to clarify code in the PR?
My hope was to introduce explicit data support with 1) no breaking changes to existing pipelines, 2) a minimal amount of API changes from the implicit counterpart, and 3) lots of data quality checks to reduce mistakes. If you see any improvements in here that I should add, please let me know! 

## How is this tested?

## Pull Request Checklist
 - [ ] Pull request includes a description of why we are doing this
 - [ ] ``CHANGELOG`` has been updated
 - [ ] Version in ``_version.py`` has been updated
 - [ ] All tests in the ``tests`` folder pass with a local build
 - [ ] ``README`` has been updated (if applicable)
 - [ ] Documentation in ``docs`` has been updated (if applicable)
 - [ ] ``requirements.txt`` and ``requirements-dev.txt`` have been recompiled (if applicable)

## Screenshots or GIFs?

2021-06-17 17:06 UTC, peterskipper requested changes
Looking good! Added testing is explicit and seems to have a lot of new coverage. I left some questions/comments.

High level, we should also have a discussion about how this affects training a weighted mashup model downstream. My current implementation relies on (re)defining the ratings matrix to hold e.g. 1 if the interaction is an order and 2 if it's a pview, and then applying a different weight to the loss. This requires the dataset to be explicit I think, but I still want to be able to use negative samples with the loss function, which I *think* might break the logic here? Maybe I shouldn't use the matrix this way and we could create a different sparse matrix holding interaction type / maybe we should change this refactor to allow for this use case since it's coming up? Let's talk it through and decide on a path forward.

2021-06-21 16:03 UTC, nathancooperjones commented on collie_recs/cross_validation.py
> +            remove_duplicate_user_item_pairs=False,
Explicit datasets don't have negative samples, so the `check_num_negative_samples_is_valid` doesn't exist!

2021-06-21 16:03 UTC, nathancooperjones commented on collie_recs/interactions/datasets.py
> +class BaseInteractions(torch.utils.data.Dataset, metaclass=ABCMeta):
It's probably way more complicated, but for me, it just makes sure that you can't just instantiate a `BaseInteractions` object - you'll get an error. It's a great way to make a parent, abstract class.

2021-06-21 16:06 UTC, nathancooperjones commented on collie_recs/model/base/base_pipeline.py
> +        # explicit losses first
I'm not sure I fully understand the question, so the answer below might not be super relevant: 

We'll only use one loss per model, either implicit or explicit. I added some data quality checks to ensure that `Interactions` objects are only used with implicit losses and `ExplicitInteractions` are only used with explicit losses. 

We'll run this loss check each time in order without checking interactions type yet, and then do that type in the actual loss calculation. 

Does that answer your question?

2021-06-21 16:06 UTC, nathancooperjones commented on collie_recs/model/base/base_pipeline.py
> +            preds = self(users, items)
Yup, you got it!

2021-06-21 16:07 UTC, nathancooperjones commented on tests/test_cross_validation.py
>  class TestSplitsWithWrongP:
Hanna suggested in a previous PR to group similar tests together into a class: https://github.com/ShopRunner/collie_recs/pull/9#discussion_r620483902

2021-06-21 16:08 UTC, nathancooperjones commented on collie_recs/metrics.py
> +        _log_metrics(model=model,
If `step is None`, the logging will still work, so no need for the `try/except` block here after all!

2021-06-21 16:09 UTC, nathancooperjones commented on collie_recs/metrics.py
> +    logger.log_metrics(metrics=metrics_dict, step=step)
Yup!!

2021-06-21 16:19 UTC, nathancooperjones commented on collie_recs/interactions/datasets.py
> -                if 0 in set(ratings):
They're allowed for explicit interactions (for now) but not for implicit interactions. This check was just moved further down in the file (line 293).

2021-06-21 16:19 UTC, nathancooperjones commented on collie_recs/interactions/datasets.py
> -                if 0 in set(ratings):
If you think there's a reason to add this check in for explicit data as well, let me know!

2021-06-21 18:48 UTC, nathancooperjones commented on collie_recs/interactions/datasets.py
> +          - **Implicit**
I'm not sure I understand this comment - where should this be moved to in the docstring?

2021-06-28 15:28 UTC, nathancooperjones commented on collie_recs/interactions/dataloaders.py
> +    For explicit data, negative sampling is not used, but batches will still be created
Here's what I'm thinking for the structure / modeling format: 

``((X, Y), Z)`` = ``((user IDs, item IDs), negative item IDs)`` = Implicit Model 
``(X, Y, Z)`` = ``(user IDs, item IDs, ratings)`` = Explicit Model 
``((X, Y), Z, C)`` = ``((user IDs, item IDs), negative item IDs, interaction type)`` = Mash Up Implicit Model 

I think the checking logic for this could be something like, roughly: 

```python
if isinstance(batch, Callable) and not isinstance(batch, torch.tensor):
    if len(batch) == 2:
        # implicit model
    elif len(batch) == 3:
        # mash up implicit
else:
    # explicit
```

How does this sound to you?

2021-07-01 19:48 UTC, peterskipper commented on collie_recs/interactions/dataloaders.py
> +    For explicit data, negative sampling is not used, but batches will still be created
Sorry for the **slow** reply. So we agree that the Mashup Implicit model would just repurpose the ratings matrix to hold the interaction type? Or would we create a different object for Mashups with a new name?

In principle this works but I'd be worried downstream that checking the `len(batch)` could cause us problems later in ways we wouldn't predict. Like if we refactor either of the model classes we might not think to check here? If possible, I think it'd be better to explicitly check the batch type or model type against a string name. If that's a huge hassle maybe we could get around it with some explicit unit tests of each data loader?

Lmk what you think.

2021-07-01 19:49 UTC, peterskipper commented on collie_recs/interactions/datasets.py
> -                if 0 in set(ratings):
no, this is great!

2021-07-01 19:54 UTC, peterskipper commented on collie_recs/model/base/base_pipeline.py
> +        # explicit losses first
nm, just got confused! This is just running checks not actually calculating a loss :dissapear:

2021-07-01 20:00 UTC, peterskipper commented on collie_recs/interactions/datasets.py
> +          - **Implicit**
Hmm no I think this is my fault. This is like markdown or sthg? I think I just misunderstood the structure. If it looks good in read the docs, I'm fine

2021-07-01 20:02 UTC, peterskipper commented
Thanks for all your comments, Nate! I'm understanding this better. I continued our discussion on how to handle implicit mashup modelds. And did you decide to add a warning when I e.g.  pass in hinge instead of adaptive_hinge in the base pipeline (see comment above)?

2021-07-01 20:26 UTC, nathancooperjones commented
> Thanks for all your comments, Nate! I'm understanding this better. I continued our discussion on how to handle implicit mashup modelds. And did you decide to add a warning when I e.g. pass in hinge instead of adaptive_hinge in the base pipeline (see comment above)?

Yes I did, see here for that warning: https://github.com/ShopRunner/collie_recs/blob/eba517872438d3b33d96fc46b54be92e8949ad9f/collie_recs/model/base/base_pipeline.py#L283-L290

2021-07-01 20:31 UTC, nathancooperjones commented on collie_recs/interactions/dataloaders.py
> +    For explicit data, negative sampling is not used, but batches will still be created
I'm not sure of a better solution for handling this right now. 

I've added a good chunk of warnings that will fail training a model without having to rely on the batch first (see something like this: https://github.com/ShopRunner/collie_recs/blob/eba517872438d3b33d96fc46b54be92e8949ad9f/collie_recs/model/base/base_pipeline.py#L557)

I'm hoping that with these extra checks in place in both the datasets and models, we won't have to only rely on the `len(batch)` method. 

For the mashup model, I think it makes sense to just repurpose the ratings matrix for this purpose. We _might_ want to create a whole separate object for that (unless there really aren't a ton of changes and it works for instances where we have and don't have this data).

2021-07-01 20:46 UTC, peterskipper commented on collie_recs/interactions/dataloaders.py
> +    For explicit data, negative sampling is not used, but batches will still be created
OK, sounds good. Do you think we can add a unit test for each data loader to pull in a small dataset, use it to make a batch, and then `assert` that the batch is the correct length and/or contains the correct items? Not sure how difficult that would be. If it's doable, that would at least prevent us from accidentally refactoring in such a way that the dataloader would get confused about the batch.

2021-07-01 20:57 UTC, nathancooperjones commented on collie_recs/interactions/dataloaders.py
> +    For explicit data, negative sampling is not used, but batches will still be created
See the tests here: 

https://github.com/ShopRunner/collie_recs/blob/6257f1b05e520c0c5352ccba875d995aeb74c40c/tests/test_interactions.py#L643

https://github.com/ShopRunner/collie_recs/blob/6257f1b05e520c0c5352ccba875d995aeb74c40c/tests/test_interactions.py#L689

https://github.com/ShopRunner/collie_recs/blob/6257f1b05e520c0c5352ccba875d995aeb74c40c/tests/test_model.py#L667

https://github.com/ShopRunner/collie_recs/blob/6257f1b05e520c0c5352ccba875d995aeb74c40c/tests/test_model.py#L876

https://github.com/ShopRunner/collie_recs/blob/6257f1b05e520c0c5352ccba875d995aeb74c40c/tests/test_model.py#L894

Is that what you had in mind? If not, I can add an additional set of tests to target this better. Let me know!

2021-07-02 17:14 UTC, peterskipper commented on collie_recs/interactions/dataloaders.py
> +    For explicit data, negative sampling is not used, but batches will still be created
I think that covers most of it! If the agreed upon formats for the data loader come in 3 flavors:
> ((X, Y), Z) = ((user IDs, item IDs), negative item IDs) = Implicit Model
> (X, Y, Z) = (user IDs, item IDs, ratings) = Explicit Model
> ((X, Y), Z, C) = ((user IDs, item IDs), negative item IDs, interaction type) = Mash Up Implicit Model

Then we should have tests for both explicit AND implicit (I def saw the explicit one, is there sthg similar for implicit? Not sure how the hdf5 tests play into this). If we are making changes to the data loader to allow for Mashup now, then we should add a test for that dataloader as well. If that comes later when I add my PR, we should obviously hold off.

2021-07-06 13:26 UTC, nathancooperjones commented on collie_recs/interactions/dataloaders.py
> +    For explicit data, negative sampling is not used, but batches will still be created
I'll add for the implicit tests a check that ensures that's the right structure of the output. Then, I think we should be fully covered for the above structure (minus the eventual mashup).

2021-07-07 14:32 UTC, peterskipper approved these changes
LGTM!

2021-07-07 14:32 UTC, merged

2021-07-07 14:33 UTC, peterskipper commented
https://media.giphy.com/media/jmS6YojdAaYw5z1LHi/giphy.gif