[DS-2940] Increase test coverage + fix Jupyter notebooks in Colab
ShopRunner/collie_recs pull request #9
Opened 2021-04-22 17:06 UTC by nathancooperjones

## Describe the big picture - why are we doing this?
Why have some tests when you can have many tests! 

In this PR, I went through missed lines in Codecov and tried to add as many tests as possible to Collie to cover those lines as well as a few extra edge cases I encountered. I time-boxed this ticket to two days of time, so it has been a painful two days writing tests, but look at this: **code coverage increased from 90% to 99%**!!! 

## Any additional details to clarify code in the PR?
In addition to adding tests and fixing some edge cases, I also updated the notebooks to fully work in Colab by regenerating the data from the ``01`` notebook if needed. No code changes here really. 

I also standardized the header of all Jupyter notebooks to be very pretty! 

## How is this tested?
Haha, great joke. 

## Pull Request Checklist
 - [X] Pull request includes a description of why we are doing this
 - [ ] ``CHANGELOG`` has been updated
 - [ ] Version in ``_version.py`` has been updated
 - [X] All tests in the ``tests`` folder pass with a local build
 - [ ] ``README`` has been updated (if applicable)
 - [ ] Documentation in ``docs`` has been updated (if applicable)
 - [X] ``requirements.txt`` and ``requirements-dev.txt`` have been recompiled (if applicable)

## Screenshots or GIFs?
![](https://media.tenor.com/images/24c8095431cc3c7c0353d60098b938dd/tenor.gif)

2021-04-26 17:34 UTC, htorrence requested changes
Lots of good work here! Looks like the test-writing craze led to some nice fixes.

Some questions/comments, and I added some wording suggestions as well on errors messages - let me know if I've gotten the context wrong on any of those.

2021-04-26 17:34 UTC, htorrence commented on tests/test_cross_validation.py
> +def test_splits_with_wrong_p(interactions_to_split):
It's generally good software engineering practice to have each test only test a single action. When you chain together a bunch of different tests like this (conceptually related, but testing different bounds and multiple functions) you loose some clarity about what happened when the test fails. With this structure it's not immediately clear what caused the failure, and it's often helpful to know if you broke all the test splits, or just the stratified split ones, or just the upper bounds, etc, and this approach will only run the test to the first failure. If you want to have the logical groupings, how about putting them in a [test class](https://docs.pytest.org/en/stable/getting-started.html#group-multiple-tests-in-a-class)?

2021-04-26 17:34 UTC, htorrence commented on tests/fixtures/model_fixtures.py
> +                                gpu_count):
Not technically part of this PR, but the use of tempfiles below to test the hdf5 work is really nice!

2021-04-26 17:34 UTC, htorrence commented on tutorials/02_matrix_factorization.ipynb
> +  "nbformat": 4,
Both reviewNB and github think most of this file changed, is it just the header or are there more actual changes to review in the notebooks?

2021-04-26 18:23 UTC, nathancooperjones commented on collie_recs/cross_validation.py
>      if len(kwargs) > 0 and [kwargs_key for kwargs_key in kwargs] != ['processes']:
`kwargs` is still ignored, but I had a worry that if you accidentally passed an argument in wrong (like `testp` instead of `test_p`) that it would just silently work and use the default incorrectly. I added this code block to ensure that we check the `kwargs` are at least expected and, if not, throw an error that hopefully helps resolve this.

2021-04-26 18:46 UTC, nathancooperjones commented on collie_recs/utils.py
> -    if min(users) != 0 or min(items) != 0:
Exactly!

2021-04-26 18:47 UTC, nathancooperjones commented on tutorials/02_matrix_factorization.ipynb
> +  "nbformat": 4,
Just the header and the cell (cell 3) re-creating the data if not loaded from the file system. Everything else is exactly the same.

2021-04-26 18:54 UTC, nathancooperjones commented on collie_recs/cross_validation.py
>      if len(kwargs) > 0 and [kwargs_key for kwargs_key in kwargs] != ['processes']:
Nevermind, removed this!

2021-04-26 18:56 UTC, nathancooperjones commented on collie_recs/model/hybrid_matrix_factorization_model.py
> +        if os.path.exists(path):
I realized the two checks were redundant, and I only needed a single check here!

2021-04-26 20:39 UTC, nathancooperjones commented on tutorials/02_matrix_factorization.ipynb
> + "cells": [
Not sure why it is showing so much difference here, but the only thing I did was combine two cells together ¯\\_(ツ)_/¯

2021-04-27 14:26 UTC, htorrence commented on tutorials/02_matrix_factorization.ipynb
> + "cells": [
Diffs on notebooks are weird. Thanks for clarifying!

2021-04-27 14:26 UTC, htorrence approved these changes
This looks great!

2021-04-27 14:28 UTC, merged